project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - weeks/**/*.qmd
  resources:
    - config/**
    - files/**

website:
  title: "IT Architektúra – Gyakorlati munkafüzet"
  navbar:
    left:
      - href: index.qmd
        text: Kezdőlap
      - href: weeks/week01/index.qmd
        text: 1. hét
      - href: weeks/week02/index.qmd
        text: 2. hét

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    smooth-scroll: true
