---
title: "IT Architektúra – Gyakorlati munkafüzet"
---

## Gyakorlati anyagok

A kurzus gyakorlati anyagai hetenként külön oldalon jelennek meg.

Az egyes heti oldalak **interaktív munkafüzetként** működnek:

- a feladatleírásokat közvetlenül a böngészőben olvashatod;
- a válaszokat ugyanazon az oldalon rögzítheted;
- a böngésző automatikusan menti a kitöltött mezőket;
- minden feladatnál – a beállításoktól függően – szintaktikai vagy AI-ellenőrzést kérhetsz;
- a **Beadás** gomb előbb összesítést mutat a kitöltöttségről, időről és hátralévő feladatokról.


## Heti gyakorlatok


### [1. hét – Első virtuális gépünk az Azure-ban](https://gmolnar2022.github.io/it-architektura-lab/weeks/week01/)

**Azure Portal → Windows 11 VM → RDP → Cloud Shell → PowerShell → Script → AI**


### [2. hét – PowerShell és automatizálás](https://gmolnar2022.github.io/it-architektura-lab/weeks/week02/)

**Skillable → Azure VM → VS Code → Azure PowerShell → RDP → Windows PowerShell → Pipeline → Változók → Script**


### [3. hét – Folyamatok, teljesítmény és Azure monitoring](weeks/week03/)

**VS Code → Azure PowerShell → Guest OS → Get-Counter → AI → Resource Graph → Azure Monitor**

### [4 hét – Hálózati eszközök Azure-ban](weeks/week04/)

**VS Code → Azure PowerShell → AI → IIS -> Web page -> Dashboard**

A további hetek folyamatosan kerülnek hozzáadásra.

